### ISSUE TITLE
Migrate all metadata documentation to opengeometadata.github.io

### ISSUE THREAD

**Issue by rmseifried** [OpenGeoMetadata/metadata-issues#12]
These ideas came from discussion of issue #11. We decided that a good place for metadata documentation would be a website associated with OpenGeoMetadata, rather than GeoBlacklight. 

See the Google doc [GeoBlacklight metadata documentation locations](https://docs.google.com/document/d/191QXbeX7W_ePKKHVZyxRcG3eV7uKTLEe90sDHjyj4Po/edit?usp=sharing) for a list of locations of current metadata documentation and notes from our discussions.

Tasks:
- [x] Spin up a GitHub page using Jekyll for **opengeometadata.github.io** (similar to [geoblacklight.github.io](https://github.com/geoblacklight/geoblacklight.github.io))
- [x] Link the new OGM site to the domain opengeometadata.org (see [geoblacklight issue 1089](https://github.com/geoblacklight/geoblacklight/issues/1089))
- [x] #27
- [x] #14
- [x] #28
- [x] Migrate content from [geoblacklight-metadata](https://github.com/geoblacklight/geoblacklight-metadata)
- [x] Update references to metadata documentation across OGM and GB universes (especially the main website's [About page](https://github.com/geoblacklight/geoblacklight.github.io)
- [x] #31 [OGM > metadatarepository wiki](https://github.com/OpenGeoMetadata/metadatarepository)
- [x] Decide where to put validation files (ideally somewhere associated with OpenGeoMetadata) currently in [GeoBlacklight > schema](https://github.com/geoblacklight/geoblacklight/tree/main/schema)
- [x] Decide what to do with the [geoblacklight-metadata](https://github.com/geoblacklight/geoblacklight-metadata) repo and the [GeoBlacklight wiki](https://github.com/geoblacklight/geoblacklight/wiki/Metadata)

**Comment by rmseifried** [comment]
Launched a bare-bones GitHub page using [Just the Docs](https://pmarsceill.github.io/just-the-docs/) (specifically, the [remote theme option](https://github.com/pmarsceill/jtd-remote)):

https://opengeometadata.github.io/

**Comment by karenmajewicz** [comment]
Should all Metadata 1.0 documentation be migrated as well?

**Comment by rmseifried** [comment]
My memory of our conversation about this was that we would aggregate all metadata-related documentation into the new OGM site (including 1.0 documentation) so that it is in a single easy-to-find place. Then archive the existing various documentations, and replace them with links to the OGM site.

**Comment by rmseifried** [comment]
There's a draft design plan for organizing the the metadata documentation at the bottom of the [GeoBlacklight metadata documentation locations](https://docs.google.com/document/d/191QXbeX7W_ePKKHVZyxRcG3eV7uKTLEe90sDHjyj4Po/edit?usp=sharing) doc. I'd love feedback on the organization!

**Comment by karenmajewicz** [comment]
I have been thinking about the task to migrate content from this repo (geoblacklight/geoblacklight-metadata). I think we are mostly talking about our workspace for GitHub issues, at this point? (The fixture examples are for the geoblacklight spec tests and are just working docs.)

Options:
- Move to OpenGeoMetadata organization into existing GitHub Pages repo
- Move to OpenGeoMetadata organization into a new repo for Metadata Interest Group
- No change: Keep in GeoBlacklight organization as is
- Keep in GeoBlacklight organization, but rename

Is there another place?  I kind of favor the idea of having a dedicated metadata working group repo along the lines of https://github.com/islandora-interest-groups/Islandora-Metadata-Interest-Group
