### ISSUE TITLE
Migrate content from the GeoBlacklight wiki

### ISSUE THREAD

**Issue by rmseifried** [OpenGeoMetadata/metadata-issues#28]
Based on approved design layout in this [Google Doc](https://docs.google.com/document/d/191QXbeX7W_ePKKHVZyxRcG3eV7uKTLEe90sDHjyj4Po/edit?usp=sharing), migrate content from the metadata sections of the [GeoBlacklight wiki](https://github.com/geoblacklight/geoblacklight/wiki/Metadata).

**Comment by rmseifried** [comment]
@karenmajewicz I'm currently working on this issue in this branch: [28-migrate-content-from-wiki](https://github.com/OpenGeoMetadata/opengeometadata.github.io/tree/28-migrate-content-from-wiki).

Before I get too much further on implementing the [new page structure we proposed](https://docs.google.com/document/d/191QXbeX7W_ePKKHVZyxRcG3eV7uKTLEe90sDHjyj4Po/edit?usp=sharing), how does this new layout look to you?

Notable changes:
* "Current Schema" lands on the previous "About Aardvark" page
* The previous "Aardvark Schema" and its children pages are now children of "Current Schema" (but note I haven't finished updating the code to make the grand-children all appear)

Still to do: add "Helpful Resources" and its children.

<img width="878" alt="Screen Shot 2022-02-22 at 1 29 41 PM" src="https://user-images.githubusercontent.com/36506059/155197444-df066f2a-1f36-4ff8-a389-2a79a166475e.png">

**Comment by karenmajewicz** [comment]
Minor suggestion: 

1. Change "About Our Schemas" to "About Our Schema" (singular)
2. Then, change "Legacy Schemas" to "Legacy Versions"?

**Comment by rmseifried** [comment]
PR to restructure the website is here: https://github.com/OpenGeoMetadata/opengeometadata.github.io/pull/22

More migration work needs to be done before this issue can be closed.

**Comment by rmseifried** [comment]
Migration work is done!
